### ISSUE TITLE
우편후-> 한정미션주얼까지 받고40가챠

### ISSUE THREAD

**Issue by leechanhs** [sanyav1/Umamusume-KR-Resetmarathon#24] opened 2022-07-25 15:12 UTC
![gift1](https://user-images.githubusercontent.com/109974936/180812381-513e7174-4375-4f78-8de4-a1b3c3382e87.png) gift1.png

![gift2](https://user-images.githubusercontent.com/109974936/180812395-989753ba-566c-44d0-b561-46e2b90ac9d3.png)gift2.png

![gift3](https://user-images.githubusercontent.com/109974936/180812396-935c9e39-91ed-45cc-a211-81d2ee628851.png)gift3.png

![gift4](https://user-images.githubusercontent.com/109974936/180812400-491298be-ac3f-4b2e-8d43-f863a0daffe6.png)gift4.png

![gift5](https://user-images.githubusercontent.com/109974936/180812409-1d7fe610-19c2-4255-a7d8-b1e0fad0724f.png)gift5.png

![gift6](https://user-images.githubusercontent.com/109974936/180812412-1cfa88db-77f5-4d47-860e-e364d73c66ba.png)gift6.png

![gift7](https://user-images.githubusercontent.com/109974936/180812417-25b5eb78-aeaf-4cc2-94a3-191d02ceb43f.png)gift7.png
UmaN\image 에 기프트1~7로 저쟁해야댐  . png 7개넣고

UmaN.xml

            <Name>noGift</Name>
            <Rect>(227, 333, 50, 22)</Rect>
            <ROI>(227, 333, 50, 22)</ROI>
            <FullROI>0</FullROI>
            <Param1>13828097</Param1>
            <Param2>998371</Param2>
            <Param3>0</Param3>
            <Param4>1658758714</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="70" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_32>

---------------------------여기밑에다가

 <Image_33>
            <Name>gift1</Name>
            <Rect>(350, 440, 19, 35)</Rect>
            <ROI>(350, 440, 19, 35)</ROI>
            <FullROI>0</FullROI>
            <Param1>12058624</Param1>
            <Param2>474102</Param2>
            <Param3>0</Param3>
            <Param4>1658754191</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_33>
        <Image_34>
            <Name>gift2</Name>
            <Rect>(352, 661, 31, 36)</Rect>
            <ROI>(352, 661, 31, 36)</ROI>
            <FullROI>0</FullROI>
            <Param1>13697025</Param1>
            <Param2>605159</Param2>
            <Param3>0</Param3>
            <Param4>1658754201</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_34>
        <Image_35>
            <Name>gift3</Name>
            <Rect>(131, 263, 35, 15)</Rect>
            <ROI>(131, 263, 35, 15)</ROI>
            <FullROI>0</FullROI>
            <Param1>13697025</Param1>
            <Param2>343036</Param2>
            <Param3>0</Param3>
            <Param4>1658754212</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_35>
        <Image_36>
            <Name>gift4</Name>
            <Rect>(132, 262, 44, 19)</Rect>
            <ROI>(132, 262, 44, 19)</ROI>
            <FullROI>0</FullROI>
            <Param1>8519680</Param1>
            <Param2>408575</Param2>
            <Param3>0</Param3>
            <Param4>1658754220</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_36>
        <Image_37>
            <Name>gift6</Name>
            <Rect>(175, 447, 46, 30)</Rect>
            <ROI>(175, 447, 46, 30)</ROI>
            <FullROI>0</FullROI>
            <Param1>14942209</Param1>
            <Param2>932839</Param2>
            <Param3>0</Param3>
            <Param4>1658754241</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_37>
        <Image_38>
            <Name>gift5</Name>
            <Rect>(158, 594, 79, 18)</Rect>
            <ROI>(158, 594, 79, 18)</ROI>
            <FullROI>0</FullROI>
            <Param1>9371648</Param1>
            <Param2>474065</Param2>
            <Param3>0</Param3>
            <Param4>1658754233</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_38>
        <Image_39>
            <Name>gift7</Name>
            <Rect>(288, 388, 83, 45)</Rect>
            <ROI>(288, 388, 83, 45)</ROI>
            <FullROI>0</FullROI>
            <Param1>9568256</Param1>
            <Param2>80882</Param2>
            <Param3>0</Param3>
            <Param4>1658754253</Param4>
            <Enable>0</Enable>
            <Group>2</Group>
            <Trg Interval="1" CheckInherit1="1" Acc="80" CheckInherit2="1" CheckShade="1" CheckEdge="0" CheckGauge="0" Gauge="70" ComboGauge="0" CheckAnimated="0" AnimatedSec="2" CheckLuaVar="0" LuaVar="" CheckNotFound="0" CheckPrint="0" ComboPrint="1"/>
            <ActCount>2</ActCount>
            <Act_1>
                <Name>이미지 표시</Name>
                <Enable>1</Enable>
                <Param/>
                <Attr/>
            </Act_1>
            <Act_2>
                <Name>마우스 입력</Name>
                <Enable>1</Enable>
                <Param>Mouse( 0 0 1  0 0 0 0 0  5 5  0.000000 0.000000  0.500000 1 )</Param>
                <Attr Input="0" Button="0" Speed="1" Base="0" Coord_x1="0" Coord_y1="0" Coord_x2="0" Coord_y2="0" Rand_x="5" Rand_y="5" PressSec1="0" PressSec2="0" Delay="0.5" Iter="1"/>
            </Act_2>
        </Image_39>
-----------------------------
추가

---------------------------------
\UmaN\action
startScript2_htvre 에서 gift1~7부분추가및 수정해주면됨

-------------------------------
Sleep(1000)

-- Input trainer info
Mouse(LBUTTON, CLICK, 123, 322, 123, 322, 0, 0, 0.3, 1, FASTER, MESSAGE)
Mouse(LBUTTON, UP, 0, 0, 0, 0, 0, 0, 0.2, 1, FASTER, MESSAGE)
Keybd('KITASAN<Enter>', FASTER, MESSAGE)
Mouse(LBUTTON, CLICK, 198, 461, 198, 461, 0, 0, 0.3, 1, FASTER, MESSAGE)
Mouse(LBUTTON, UP, 0, 0, 0, 0, 0, 0, 0.2, 1, FASTER, MESSAGE)

err = Loopstep("trainerOK", "skipGift", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("skipGift", "notifications", LOOP_ERR_LARGE*2, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("notifications", "mainStory", LOOP_ERR_LARGE, {true, 374,25})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("mainStory", "umaStory", LOOP_ERR_LARGE, {true, 202,464})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("umaStory", "giftBox", LOOP_ERR_LARGE, {true, 201,658})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("giftBox", "getAll", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("getAll", "getOK", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("getOK", "noGift", LOOP_ERR_LARGE, {true, 201, 658})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("noGift", "gift1", LOOP_ERR_LARGE, {true, 136, 668})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift1", "gift2", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift2", "gift3", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift3", "gift4", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift4", "gift5", LOOP_ERR_LARGE, {true, 207, 595})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift5", "gift6", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift6", "gift7", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("gift7", "goGacha", LOOP_ERR_LARGE, {true, 113, 656})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("goGacha", "gachaStandby", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

-------------------------------------------------------------

**Comment by sanyav1** [comment] 2022-07-25 15:15
마침 작성중이었는데 방식은 비슷하네요

```lua
err = Loopstep("doNotPick", "exitGacha", LOOP_ERR_SMALL, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("exitGacha", "toHome", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("toHome", "toMenu", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("toMenu", "toRecord", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("toRecord", "skipRecord", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("skipRecord", "closeRecord", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("closeRecord", "closeReward", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("closeReward", "exitRecord", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("exitRecord", "closeMenu", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("closeMenu", "giftBox", LOOP_ERR_LARGE, {true, 0,0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("giftBox", "getAll", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("getAll", "noGift", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("noGift", "goGacha", LOOP_ERR_LARGE, {true, 113, 656})
if ErrorJudge(err) > 0 then return 0 end

err = Loopstep("goGacha", "gachaStandby", LOOP_ERR_LARGE, {true, 0, 0})
if ErrorJudge(err) > 0 then return 0 end
```

다른 에러도 잡고 있어서 잡히는 대로 반영하겠습니다.

**Comment by sanyav1** [comment] 2022-07-25 15:16
duplicate of #3

**Closed as completed** 2022-07-25 15:26 UTC
Labels: duplicate
